# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- VitePress Build Steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: docs/snappy-docs
        run: npm ci

      - name: Build VitePress
        working-directory: docs/snappy-docs
        run: npm run build

      - name: Ensure target folder exists
        run: mkdir -p docs/snappy

      # --- Existing Pages deployment steps ---
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/snappy # deploy only the built folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
